/*
 * This file is generated by jOOQ.
 */
package models;


import javax.annotation.Generated;

import models.tables.Sample;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.sample</code>.
     */
    public static final Sample SAMPLE = models.tables.Sample.SAMPLE;
}
